import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    backgroundGradient: {
        flex: 1,
    },
    container: {
        flex: 1,
        paddingHorizontal: 24,
        paddingTop: 16,
    },
    header: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 24,
    },
    screenTitle: {
        fontSize: 32,
        fontWeight: '800',
        color: '#16161A',
        fontFamily: 'Inter_800ExtraBold',
    },
    filterButton: {
        width: 40,
        height: 40,
        borderRadius: 12,
        backgroundColor: '#EEEAFB',
        justifyContent: 'center',
        alignItems: 'center',
    },
    loadingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#F8F9FF',
    },
    itemContainer: {
        borderRadius: 20,
        marginBottom: 16,
        shadowColor: '#7F5AF0',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.1,
        shadowRadius: 16,
        elevation: 5,
        overflow: 'hidden',
    },
    gradientBackground: {
        padding: 20,
    },
    headerRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        marginBottom: 12,
    },
    titleWrapper: {
        flex: 1,
        marginRight: 12,
    },
    title: {
        fontSize: 18,
        fontWeight: '700',
        color: '#16161A',
        lineHeight: 24,
        fontFamily: 'Inter_700Bold',
    },
    content: {
        fontSize: 15,
        color: '#5F6C7B',
        marginBottom: 16,
        lineHeight: 22,
        fontFamily: 'Inter_400Regular',
    },
    footerRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    dateBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#EEEAFB',
        borderRadius: 12,
        paddingVertical: 6,
        paddingHorizontal: 10,
    },
    date: {
        fontSize: 12,
        color: '#7F5AF0',
        fontWeight: '600',
        marginLeft: 6,
        fontFamily: 'Inter_600SemiBold',
    },
    chevronCircle: {
        width: 32,
        height: 32,
        borderRadius: 16,
        backgroundColor: '#EEEAFB',
        justifyContent: 'center',
        alignItems: 'center',
    },
    priorityBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        borderRadius: 12,
        paddingVertical: 6,
        paddingHorizontal: 10,
    },
    priorityText: {
        fontSize: 12,
        fontWeight: '600',
        marginLeft: 6,
        fontFamily: 'Inter_600SemiBold',
    },
    categoryBadge: {
        backgroundColor: '#EEEAFB',
        borderRadius: 6,
        paddingVertical: 2,
        paddingHorizontal: 8,
        alignSelf: 'flex-start',
        marginTop: 8,
    },
    categoryText: {
        fontSize: 12,
        color: '#7F5AF0',
        fontWeight: '600',
        fontFamily: 'Inter_600SemiBold',
    },
    listContent: {
        paddingBottom: 24,
    },
    emptyContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 40,
    },
    emptyTitle: {
        textAlign: 'center',
        marginTop: 16,
        fontSize: 18,
        color: '#16161A',
        fontWeight: '700',
        fontFamily: 'Inter_700Bold',
    },
    emptySubtitle: {
        textAlign: 'center',
        marginTop: 4,
        fontSize: 14,
        color: '#5F6C7B',
        fontWeight: '500',
        fontFamily: 'Inter_500Medium',
    },
});