import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#f5f6fa',
    },
    header: {
        padding: 24,
        paddingBottom: 16,
        marginBottom: 8,
    },
    highPriority: {
        backgroundColor: '#ffecec',
        borderBottomWidth: 4,
        borderBottomColor: '#e74c3c',
    },
    mediumPriority: {
        backgroundColor: '#fff5e6',
        borderBottomWidth: 4,
        borderBottomColor: '#f39c12',
    },
    lowPriority: {
        backgroundColor: '#e8f8f0',
        borderBottomWidth: 4,
        borderBottomColor: '#2ecc71',
    },
    headerTopRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 8,
    },
    priority: {
        fontSize: 12,
        fontWeight: '800',
        letterSpacing: 1,
        color: '#2d3436',
    },
    date: {
        fontSize: 12,
        color: '#636e72',
    },
    title: {
        fontSize: 24,
        fontWeight: '800',
        color: '#2d3436',
        lineHeight: 32,
    },
    contentContainer: {
        padding: 24,
        paddingTop: 16,
    },
    content: {
        fontSize: 16,
        color: '#2d3436',
        lineHeight: 24,
        marginTop: 16,
    },
    media: {
        width: '100%',
        height: 240,
        borderRadius: 12,
        marginBottom: 16,
        backgroundColor: '#dfe6e9',
    },
    reactionsContainer: {
        flexDirection: 'row',
        justifyContent: 'space-around',
        paddingVertical: 12,
        backgroundColor: '#ffffff',
        marginHorizontal: 16,
        borderRadius: 24,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 6,
        elevation: 2,
        marginBottom: 16,
    },
    reactionButton: {
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 16,
    },
    selectedReaction: {
        backgroundColor: '#e8e8ff',
    },
    reactionText: {
        fontSize: 16,
    },
    commentsContainer: {
        flex: 1,
        backgroundColor: '#ffffff',
        borderTopLeftRadius: 24,
        borderTopRightRadius: 24,
        padding: 24,
        paddingBottom: 0,
    },
    commentsHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 16,
    },
    commentsTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: '#2d3436',
        marginLeft: 8,
    },
    commentInputContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 20,
    },
    commentInput: {
        flex: 1,
        borderWidth: 1,
        borderColor: '#dfe6e9',
        borderRadius: 20,
        padding: 14,
        minHeight: 50,
        marginRight: 10,
        backgroundColor: '#f5f6fa',
        fontSize: 14,
        color: '#2d3436',
    },
    commentButton: {
        backgroundColor: '#6c5ce7',
        borderRadius: 20,
        width: 50,
        height: 50,
        justifyContent: 'center',
        alignItems: 'center',
    },
    commentItem: {
        backgroundColor: '#f5f6fa',
        borderRadius: 16,
        padding: 16,
        marginBottom: 12,
    },
    commentHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 6,
    },
    commentAuthor: {
        fontWeight: '600',
        color: '#2d3436',
        fontSize: 14,
    },
    commentDate: {
        color: '#b2bec3',
        fontSize: 12,
    },
    commentContent: {
        color: '#636e72',
        lineHeight: 20,
        fontSize: 14,
    },
    noCommentsContainer: {
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 40,
    },
    noCommentsText: {
        color: '#b2bec3',
        marginTop: 8,
        fontSize: 14,
    },
    errorContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 40,
    },
    errorText: {
        marginTop: 16,
        color: '#e74c3c',
        fontSize: 16,
        fontWeight: '500',
    },
    emptyContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 40,
    },
    emptyText: {
        marginTop: 16,
        color: '#b2bec3',
        fontSize: 16,
        fontWeight: '500',
    },
});