import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#F8F9FF',
    },
    headerGradient: {
        paddingHorizontal: 24,
        paddingTop: 24,
        paddingBottom: 32,
        borderBottomLeftRadius: 32,
        borderBottomRightRadius: 32,
    },
    highPriorityGradient: {
        backgroundColor: '#FFEEEE',
        backgroundGradientFrom: '#FFEEEE',
        backgroundGradientTo: '#FFF6F6',
    },
    mediumPriorityGradient: {
        backgroundColor: '#FFF4E5',
        backgroundGradientFrom: '#FFF4E5',
        backgroundGradientTo: '#FFFBF5',
    },
    lowPriorityGradient: {
        backgroundColor: '#F0FFF7',
        backgroundGradientFrom: '#F0FFF7',
        backgroundGradientTo: '#F8FFFC',
    },
    headerTopRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 16,
    },
    priorityBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 6,
        paddingHorizontal: 12,
        borderRadius: 16,
    },
    highPriorityBadge: {
        backgroundColor: '#FF4D4D20',
    },
    mediumPriorityBadge: {
        backgroundColor: '#FFAA3320',
    },
    lowPriorityBadge: {
        backgroundColor: '#2CB67D20',
    },
    priorityText: {
        fontSize: 12,
        fontWeight: '700',
        marginLeft: 6,
        fontFamily: 'Inter_700Bold',
    },
    highPriorityText: {
        color: '#FF4D4D',
    },
    mediumPriorityText: {
        color: '#FFAA33',
    },
    lowPriorityText: {
        color: '#2CB67D',
    },
    date: {
        fontSize: 12,
        color: '#7F5AF0',
        fontWeight: '600',
        fontFamily: 'Inter_600SemiBold',
    },
    title: {
        fontSize: 28,
        fontWeight: '800',
        color: '#16161A',
        lineHeight: 36,
        marginBottom: 8,
        fontFamily: 'Inter_800ExtraBold',
    },
    contentContainer: {
        padding: 24,
        paddingTop: 16,
    },
    content: {
        fontSize: 16,
        color: '#5F6C7B',
        lineHeight: 26,
        marginBottom: 24,
        fontFamily: 'Inter_400Regular',
    },
    media: {
        width: '100%',
        height: 240,
        borderRadius: 20,
        marginBottom: 24,
        backgroundColor: '#EEEAFB',
        overflow: 'hidden',
    },
    reactionsContainer: {
        flexDirection: 'row',
        justifyContent: 'space-around',
        paddingVertical: 12,
        backgroundColor: '#FFFFFF',
        marginHorizontal: 24,
        borderRadius: 24,
        shadowColor: '#7F5AF0',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.1,
        shadowRadius: 16,
        elevation: 8,
        marginBottom: 24,
    },
    reactionButton: {
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderRadius: 16,
        flexDirection: 'row',
        alignItems: 'center',
    },
    selectedReaction: {
        backgroundColor: '#7F5AF020',
    },
    reactionText: {
        fontSize: 16,
        marginLeft: 6,
        fontFamily: 'Inter_600SemiBold',
    },
    selectedReactionText: {
        color: '#7F5AF0',
    },
    commentsContainer: {
        flex: 1,
        backgroundColor: '#FFFFFF',
        borderTopLeftRadius: 32,
        borderTopRightRadius: 32,
        padding: 24,
        paddingBottom: 0,
    },
    commentsHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 24,
    },
    commentsTitle: {
        fontSize: 20,
        fontWeight: '700',
        color: '#16161A',
        marginLeft: 12,
        fontFamily: 'Inter_700Bold',
    },
    commentInputContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 24,
    },
    commentInput: {
        flex: 1,
        borderWidth: 1,
        borderColor: '#EEEAFB',
        borderRadius: 24,
        padding: 16,
        minHeight: 56,
        marginRight: 12,
        backgroundColor: '#F8F9FF',
        fontSize: 15,
        color: '#16161A',
        fontFamily: 'Inter_400Regular',
    },
    commentButton: {
        backgroundColor: '#7F5AF0',
        borderRadius: 24,
        width: 56,
        height: 56,
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#7F5AF0',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.2,
        shadowRadius: 8,
        elevation: 4,
    },
    commentItem: {
        backgroundColor: '#F8F9FF',
        borderRadius: 20,
        padding: 20,
        marginBottom: 16,
    },
    commentHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 8,
    },
    commentAuthor: {
        fontWeight: '600',
        color: '#16161A',
        fontSize: 15,
        fontFamily: 'Inter_600SemiBold',
    },
    commentDate: {
        color: '#B8C1EC',
        fontSize: 12,
        fontFamily: 'Inter_500Medium',
    },
    commentContent: {
        color: '#5F6C7B',
        lineHeight: 22,
        fontSize: 15,
        fontFamily: 'Inter_400Regular',
    },
    noCommentsContainer: {
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 40,
    },
    noCommentsText: {
        color: '#B8C1EC',
        marginTop: 16,
        fontSize: 15,
        fontFamily: 'Inter_500Medium',
    },
    loadingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#F8F9FF',
    },
    errorContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 40,
    },
    errorText: {
        marginTop: 24,
        color: '#FF4D4D',
        fontSize: 16,
        fontWeight: '600',
        fontFamily: 'Inter_600SemiBold',
    },
    emptyContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 40,
    },
    emptyTitle: {
        marginTop: 24,
        color: '#16161A',
        fontSize: 18,
        fontWeight: '700',
        fontFamily: 'Inter_700Bold',
    },
    emptySubtitle: {
        marginTop: 8,
        color: '#B8C1EC',
        fontSize: 14,
        fontFamily: 'Inter_400Regular',
    },
    floatingActionButton: {
        position: 'absolute',
        right: 24,
        bottom: 24,
        width: 56,
        height: 56,
        borderRadius: 28,
        backgroundColor: '#7F5AF0',
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 8,
    },
    keyboardToolbar: {
        height: 44,
        justifyContent: 'flex-end',
        alignItems: 'flex-end',
        paddingHorizontal: 16,
        backgroundColor: '#f5f5f5',
        borderTopWidth: 1,
        borderTopColor: '#e5e5e5',
    },
    doneText: {
        color: '#7F5AF0',
        fontSize: 16,
        fontWeight: '600',
    },
    keyboardAvoidingView: {
        flex: 1,
    },
});