import { StyleSheet, Platform, Dimensions } from "react-native";
import { LinearGradient } from "expo-linear-gradient";

const { width, height } = Dimensions.get('window');

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#f8fafc',
    },
    gradientBackground: {
        position: 'absolute',
        left: 0,
        right: 0,
        top: 0,
        height: height * 0.25,
        borderBottomLeftRadius: 32,
        borderBottomRightRadius: 32,
    },
    scrollContainer: {
        paddingHorizontal: 28,
        paddingTop: 24,
        paddingBottom: 40,
    },
    header: {
        marginBottom: 32,
        alignItems: 'center',
    },
    heading: {
        fontSize: 28,
        fontWeight: '800',
        color: '#0f172a',
        marginBottom: 8,
        fontFamily: Platform.OS === 'ios' ? 'SF Pro Display' : 'Roboto',
        letterSpacing: -0.5,
    },
    subheading: {
        fontSize: 16,
        color: '#64748b',
        textAlign: 'center',
        paddingHorizontal: 20,
        lineHeight: 24,
    },
    inputContainer: {
        marginBottom: 24,
    },
    label: {
        fontSize: 14,
        fontWeight: '600',
        color: '#475569',
        marginBottom: 8,
        marginLeft: 4,
    },
    input: {
        backgroundColor: '#ffffff',
        borderRadius: 14,
        paddingHorizontal: 18,
        paddingVertical: 16,
        fontSize: 16,
        borderWidth: 1,
        borderColor: '#e2e8f0',
        shadowColor: '#0f172a',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 6,
        elevation: 2,
    },
    descriptionInput: {
        height: 120,
        textAlignVertical: 'top',
    },
    uploadButton: {
        backgroundColor: '#3b82f6',
        borderRadius: 14,
        paddingVertical: 14,
        alignItems: 'center',
        marginBottom: 20,
        shadowColor: '#3b82f6',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.2,
        shadowRadius: 8,
        elevation: 6,
    },
    uploadButtonText: {
        color: '#ffffff',
        fontSize: 16,
        fontWeight: '600',
    },
    mediaPreview: {
        width: '100%',
        height: 220,
        borderRadius: 14,
        marginBottom: 24,
        borderWidth: 1,
        borderColor: '#e2e8f0',
    },
    submitButton: {
        backgroundColor: '#ef4444',
        borderRadius: 16,
        paddingVertical: 18,
        marginTop: 16,
        shadowColor: '#ef4444',
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.3,
        shadowRadius: 12,
        elevation: 8,
    },
    buttonText: {
        color: '#ffffff',
        fontSize: 16,
        fontWeight: '600',
        textAlign: 'center',
    },
    modalContainer: {
        backgroundColor: 'white',
        paddingHorizontal: 30,
        paddingVertical: 30,
        borderRadius: 24,
        minHeight: 360,
    },
    modalIcon: {
        width: 60,
        height: 60,
        marginBottom: 24,
        alignSelf: 'center',
        tintColor: '#f59e0b',
    },
    modalTitle: {
        fontSize: 24,
        fontWeight: '800',
        marginBottom: 16,
        textAlign: 'center',
        color: '#0f172a',
    },
    modalText: {
        fontSize: 16,
        marginBottom: 32,
        textAlign: 'center',
        color: '#475569',
        lineHeight: 24,
    },
    floatingDecoration: {
        position: 'absolute',
        width: 200,
        height: 200,
        borderRadius: 100,
        backgroundColor: 'rgba(239, 68, 68, 0.05)',
        top: -50,
        right: -50,
    },
    floatingDecoration2: {
        position: 'absolute',
        width: 150,
        height: 150,
        borderRadius: 75,
        backgroundColor: 'rgba(239, 68, 68, 0.03)',
        bottom: -30,
        left: -30,
    },
    iconContainer: {
        alignItems: 'center',
        marginBottom: 24,
    },
    iconBackground: {
        backgroundColor: 'rgba(239, 68, 68, 0.1)',
        width: 100,
        height: 100,
        borderRadius: 50,
        justifyContent: 'center',
        alignItems: 'center',
    },
    icon: {
        width: 50,
        height: 50,
        tintColor: '#ef4444',
    },
});