import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        position: "relative",
        backgroundColor: "#fff",
    },
    gradientBackground: {
        position: "absolute",
        left: 0,
        right: 0,
        top: 0,
        bottom: 0,
    },
    floatingDecoration: {
        position: "absolute",
        width: 200,
        height: 200,
        borderRadius: 100,
        backgroundColor: "rgba(254, 202, 202, 0.5)",
        top: -50,
        right: -50,
    },
    floatingDecoration2: {
        position: "absolute",
        width: 150,
        height: 150,
        borderRadius: 75,
        backgroundColor: "rgba(254, 202, 202, 0.4)",
        bottom: -50,
        left: -50,
    },
    scrollContainer: {
        padding: 20,
        paddingBottom: 40,
    },
    header: {
        alignItems: "center",
        marginBottom: 30,
    },
    iconContainer: {
        marginBottom: 20,
    },
    iconBackground: {
        backgroundColor: "#fee2e2",
        width: 80,
        height: 80,
        borderRadius: 40,
        justifyContent: "center",
        alignItems: "center",
    },
    icon: {
        width: 40,
        height: 40,
    },
    heading: {
        fontSize: 24,
        fontWeight: "bold",
        color: "#1e293b",
        marginBottom: 8,
    },
    subheading: {
        fontSize: 14,
        color: "#64748b",
        textAlign: "center",
        maxWidth: "80%",
    },
    inputContainer: {
        marginBottom: 20,
    },
    label: {
        fontSize: 16,
        color: "#1e293b",
        marginBottom: 8,
        fontWeight: "500",
    },
    input: {
        backgroundColor: "#f8fafc",
        borderWidth: 1,
        borderColor: "#e2e8f0",
        borderRadius: 10,
        padding: 15,
        fontSize: 16,
        color: "#0f172a",
    },
    descriptionInput: {
        height: 120,
        textAlignVertical: "top",
    },
    uploadButton: {
        backgroundColor: "#f1f5f9",
        borderWidth: 1,
        borderColor: "#e2e8f0",
        borderRadius: 10,
        padding: 15,
        alignItems: "center",
        marginBottom: 15,
    },
    uploadButtonText: {
        color: "#334155",
        fontWeight: "500",
    },
    mediaPreview: {
        width: "100%",
        height: 200,
        borderRadius: 10,
    },
    submitButton: {
        backgroundColor: "#ef4444",
        borderRadius: 10,
        padding: 18,
        alignItems: "center",
        marginTop: 10,
    },
    buttonText: {
        color: "#ffffff",
        fontWeight: "600",
        fontSize: 16,
    },
    // Update the modal-related styles in ir_styles.js:
    modalOverlay: {
        position: "absolute",
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: "rgba(0,0,0,0.7)",
        justifyContent: "center",
        alignItems: "center",
        padding: 20,
    },
    modalContainer: {
        backgroundColor: "white",
        borderRadius: 20,
        padding: 30,
        width: "90%",
        maxWidth: 400,
        shadowColor: "#000",
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 4,
        elevation: 5,
    },
    modalIcon: {
        width: 60,
        height: 60,
        alignSelf: "center",
        marginBottom: 20,
        tintColor: "#ef4444",
    },
    modalTitle: {
        fontSize: 22,
        fontWeight: "bold",
        textAlign: "center",
        marginBottom: 15,
        color: "#1e293b",
    },
    modalText: {
        fontSize: 16,
        color: "#64748b",
        textAlign: "center",
        marginBottom: 30,
        lineHeight: 24,
    },
    modalProceedButton: {
        marginBottom: 15,
        backgroundColor: "#ef4444",
        borderRadius: 10,
        paddingVertical: 15,
    },
    modalCancelButton: {
        backgroundColor: "#64748b",
        borderRadius: 10,
        paddingVertical: 15,
    },
    permissionButton: {
        marginTop: 20,
        backgroundColor: "#ef4444",
    },
    cameraContainer: {
        flex: 1,
    },
    camera: {
        flex: 1,
    },
    cameraControls: {
        position: "absolute",
        bottom: 40,
        left: 0,
        right: 0,
        flexDirection: "row",
        justifyContent: "center",
        alignItems: "center",
        gap: 20,
    },
    cameraButton: {
        width: 70,
        height: 70,
        borderRadius: 35,
        backgroundColor: "rgba(255,255,255,0.3)",
        justifyContent: "center",
        alignItems: "center",
    },
    cameraButtonInner: {
        width: 60,
        height: 60,
        borderRadius: 30,
        backgroundColor: "white",
    },
    flipButton: {
        padding: 15,
        backgroundColor: "rgba(255,255,255,0.3)",
        borderRadius: 10,
    },
    flipButtonText: {
        color: "white",
        fontWeight: "bold",
    },
    closeButton: {
        padding: 15,
        backgroundColor: "rgba(255,255,255,0.3)",
        borderRadius: 10,
    },
    closeButtonText: {
        color: "white",
        fontWeight: "bold",
    },
    buttonContainer: {
        borderRadius: 10,
        overflow: "hidden",
    },
});