import { StyleSheet, Platform, Dimensions } from "react-native";
import { LinearGradient } from "expo-linear-gradient";

const { width, height } = Dimensions.get('window');

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#fafcff',
    },
    gradientBackground: {
        position: 'absolute',
        left: 0,
        right: 0,
        top: 0,
        height: height * 0.4,
        borderBottomLeftRadius: 40,
        borderBottomRightRadius: 40,
    },
    scrollContainer: {
        paddingHorizontal: 30,
        paddingTop: 35,
        paddingBottom: 30,
    },
    header: {
        marginBottom: 20,
    },
    heading: {
        fontSize: 32,
        fontWeight: '800',
        color: '#0f172a',
        marginBottom: 8,
        fontFamily: Platform.OS === 'ios' ? 'SF Pro Display' : 'Roboto',
        letterSpacing: -0.5,
    },
    subheading: {
        fontSize: 16,
        color: '#64748b',
        lineHeight: 22,
        fontFamily: Platform.OS === 'ios' ? 'SF Pro Text' : 'Roboto',
    },
    cardContainer: {
        borderRadius: 24,
        marginBottom: 20,
        shadowColor: '#0f172a',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.08,
        shadowRadius: 16,
        elevation: 8,
    },
    card: {
        backgroundColor: '#ffffff',
        borderRadius: 24,
        padding: 22,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.3)',
        overflow: Platform.OS === 'android' ? 'hidden' : undefined,
    },
    cardGradient: {
        position: 'absolute',
        top: 0,
        left: Platform.OS === 'ios' ? 1 : 0,
        right: Platform.OS === 'ios' ? 1 : 0,
        height: 4,
        borderTopLeftRadius: Platform.OS === 'ios' ? 23 : 24,
        borderTopRightRadius: Platform.OS === 'ios' ? 23 : 24,
    },
    label: {
        fontSize: 13,
        fontWeight: '600',
        color: '#64748b',
        marginBottom: 12,
        letterSpacing: 0.8,
        textTransform: 'uppercase',
    },
    pickerContainer: {
        backgroundColor: '#f8fafc',
        borderRadius: 14,
        paddingHorizontal: 16,
        paddingVertical: 8,
        borderWidth: 1,
        borderColor: '#e2e8f0',
    },
    picker: {
        color: '#0f172a',
        fontSize: 16,
    },
    submitButton: {
        marginTop: 20,
        borderRadius: 16,
        height: 56,
        shadowColor: '#2563eb',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.2,
        shadowRadius: 16,
        elevation: 12,
    },
    iconContainer: {
        alignItems: 'center',
        marginBottom: 25,
        marginTop: 5,
    },
    iconBackground: {
        backgroundColor: 'rgba(37, 99, 235, 0.1)',
        width: 100,
        height: 100,
        borderRadius: 50,
        justifyContent: 'center',
        alignItems: 'center',
    },
    icon: {
        width: 50,
        height: 50,
        tintColor: '#2563eb',
    },
    floatingDecoration: {
        position: 'absolute',
        width: 180,
        height: 180,
        borderRadius: 90,
        backgroundColor: 'rgba(37, 99, 235, 0.05)',
        top: -40,
        right: -40,
    },
    floatingDecoration2: {
        position: 'absolute',
        width: 120,
        height: 120,
        borderRadius: 60,
        backgroundColor: 'rgba(37, 99, 235, 0.03)',
        bottom: -20,
        left: -20,
    },
});